# Generated by Django 4.2.5 on 2023-10-02 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custombloguser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='custombloguser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
