# Generated by Django 4.2.5 on 2023-10-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_featureimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='custombloguser',
            name='authorLevel',
            field=models.IntegerField(blank=True, choices=[(2, 'Level 3 Author'), (3, 'Level 4 Author'), (1, 'Level 1 Author')], null=True),
        ),
        migrations.AddField(
            model_name='custombloguser',
            name='bio',
            field=models.CharField(default='/', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='custombloguser',
            name='socialLink1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='custombloguser',
            name='socialLink2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='custombloguser',
            name='socialLink3',
            field=models.URLField(blank=True, null=True),
        ),
    ]
