# Generated by Django 4.2.5 on 2023-10-04 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_custombloguser_authorlevel_custombloguser_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custombloguser',
            name='total_followers',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='custombloguser',
            name='total_following',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='custombloguser',
            name='authorLevel',
            field=models.IntegerField(choices=[(3, 'Level 4 Author'), (1, 'Level 1 Author'), (2, 'Level 3 Author')], default=1),
        ),
        migrations.CreateModel(
            name='user_follow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subscribed_date', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='follower_user', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='main_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-subscribed_date',),
                'unique_together': {('follower', 'following')},
            },
        ),
    ]
