# Generated by Django 4.2.5 on 2023-10-04 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_custombloguser_total_followers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custombloguser',
            name='authorLevel',
            field=models.IntegerField(choices=[(3, 'Level 4 Author'), (2, 'Level 3 Author'), (1, 'Level 1 Author')], default=1),
        ),
    ]
