# Generated by Django 4.2.5 on 2023-10-04 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_custombloguser_authorlevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custombloguser',
            name='authorLevel',
            field=models.IntegerField(choices=[(1, 'Level 1 Author'), (3, 'Level 4 Author'), (2, 'Level 3 Author')], default=1),
        ),
    ]
