# Generated by Django 4.2.5 on 2023-10-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_custombloguser_authorlevel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custombloguser',
            name='totalcomment',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='custombloguser',
            name='totalpost',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='custombloguser',
            name='authorLevel',
            field=models.IntegerField(choices=[(2, 'Level 2 Author'), (1, 'Level 1 Author'), (3, 'Level 3 Author')], default=1),
        ),
    ]
