# Generated by Django 4.2.5 on 2023-10-05 18:11

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_custombloguser_totalreply_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custombloguser',
            name='bio',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='custombloguser',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image'),
        ),
    ]
