# Generated by Django 4.2.5 on 2023-10-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_comment_post_alter_comment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custombloguser',
            name='authorLevel',
            field=models.IntegerField(choices=[(2, 'Level 2 Author'), (1, 'Level 1 Author'), (3, 'Level 3 Author')], default=1),
        ),
    ]
